title: 'Educational Material'
updated_by: 276fbad6-728b-4736-83b8-2d760b0bf40c
updated_at: 1697675758
blueprint: category
content: 'Because period poverty involves not only a lack of access to menstrual products, but also to menstrual education, we incorporate educational programming to inform individuals on how to safely maneuver menstruation. This page has a bunch of resource you can explore to learn more.'
